### ISSUE TITLE
Immersive Engineering Garden Cloche fertilizer

### ISSUE THREAD

**Issue by dash16** [Freebi85/Explorico_Classic#12]
The only fertilizer that seems to work in Garden Cloches is Bone Meal.  I'd expect Industrial Foregoing Fertilizer, Thermal Expansion Phyto-Gro or possibly Mystical Agriculture's Mystical Fertilizer to work and increase growth speed.

**Comment by Freebi85** [comment]
Thank you for the heads up. I will add all of them in upcoming patch :)
Industrial Fertilizer < Thermal < Mystical
