### ISSUE TITLE
Fireworks Rocket is missing recipe, use in Mycelial Generator

### ISSUE THREAD

**Issue by dash16** [Freebi85/Explorico_Classic#13]
Vanilla Firework Rockets don't have a recipe per JEI, but I can still craft them with 2 gunpowder and 1 paper.  But I can't use Firework Rockets as fuel for Industrial Foregoing's Rocket Mycelial Generator.

**Comment by Freebi85** [comment]
We had this JEI issue already back in 1.12 for some reason. I can't fix this on my end. Reporting to JEI required.
Rockets in this generator will crash right now and are not available until the devs gonna fix that 👍

**Comment by Freebi85** [comment]
I got tired of waiting and implemented my own version in JEI. -> Fixed in next update.
Industrial Foregoing's Rocket Mycelial Generator accepts now rockets again. -> Fixed in next update.
