### ISSUE TITLE
Can't craft Selfish Belt

### ISSUE THREAD

**Issue by dash16** [Freebi85/Explorico_Classic#16]
The recipe for Mana and Artifice > Selfish Belt requires a vanilla trapped chest.  The Quark variants don't seem to be working.

**Comment by Freebi85** [comment]
Thank you, gonna look into it to unify and/or tag this trapdoors and its recipes as well. 🍻

**Comment by Freebi85** [comment]
Fixed in next version.

**Comment by Freebi85** [comment]
Manaweaving seems to refuse tagged items. However, fixed with my own custom function in next update.
