### ISSUE TITLE
Weird JEI interaction when viewing Pattern Terminal

### ISSUE THREAD

**Issue by dash16** [Freebi85/Explorico_Classic#17]
When I open the Applied Energistics Pattern Terminal and click an item in JEI to see the recipe, instead of displaying the recipe on left click it tries to pick up the item from the list.  A line connects the item back to where it was pulled from, and I can drag and drop it onto the recipe/crafting grid but the recipe doesn't display.  If I right click an item in JEI, I see the recipes that use that item.  I can then left click the item again, and it's recipe is displayed, and can be added to the Pattern Terminal by pressing the plus button.  Very odd.

**Comment by Freebi85** [comment]
Hello :D 
I've already heard about this from other packs as well. I'll take a look at the latest JEi update that was released 3 days ago. Older versions that have worked "well" so far unfortunately have many dupes. Therefore, I hesitate a bit with downgrade. Lemme see.
🍺

**Comment by Freebi85** [comment]
Solved in next update.
