### ISSUE TITLE
Applied Energistics Patterns aren't rendering

### ISSUE THREAD

**Issue by dash16** [Freebi85/Explorico_Classic#19]
When you create an encoded pattern, the default behavior for the pattern is to replace the placeholder pattern icon with the icon for the item you've encoded.  You can hold down shift, which will change this preview back to the placeholder pattern icon.  After 3.1, the behavior is reversed and patterns only display their encoded item when holding shift.  This makes scrolling through lists of patterns, such as in the Interface Terminal, more difficult because you can't scroll while holding Shift.

**Comment by Freebi85** [comment]
Hello :D
While I understand the problem, I don't know if this is a new "feature" or a bug that slipped into the current AE2 update. 
Either way, this is a mechanic that I could not change on my own. This would have to be reported directly to AE2. Either as a bug or enhancement. (Unless that was done as config or new keybind input which I doubt in this case)

Cheers

**Comment by dash16** [comment]
Ah, reproduced with just AE2 and JEI installed.  Definitely an AE2 bug, submitting there: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5258
