### ISSUE TITLE
1.7 Spawning Issues

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_Classic#2]
(this ticket will be updated as new information is discovered)

Playing Explorico 1.7 SMP, with the following specs:
Forge: 1.16.4-35.1.36-universal
Ice&Fire: 2.1.5-1.16.4
Quark: r2.4-293
Astral Sorcery: 1.16.4-1.13.9

In darkened caves within rendering distance, Quark Toretices and Ice&Fire Cave Trolls seem to spawn without limit.  This is despite the Astral Sorcery ritual Lucerna being active in the area.  I see two issues:

1) Toretices are spawning with no spawn cap.  An option needs to be added to limit and/or toggle this on/off.
2) Cave Trolls are spawning despite an effect/ritual supposedly preventing hostile mobs from spawning.

Thanks.
![image](https://user-images.githubusercontent.com/10191173/104518864-6b7a6100-55c6-11eb-9866-5a1a6367eb64.png)

**Comment by Danekjovax** [comment]
iceandfire-common.toml
line 226:
	"Troll Spawn Weight" = 4
This could be changed to 2-3, though this only seems to govern rarity, not persistence, but may help a little.

**Comment by Danekjovax** [comment]
I see no options for limiting the spawning of the Toretoices.  Cyclic's mod dev claims it's not adding mobs, so more research will be needed to find out where they're coming from.

**Comment by Danekjovax** [comment]
Updated with Quark ticket (I incorrectly listed Toretoices as a Cyclic mob when they're in fact Quark).

**Comment by Freebi85** [comment]
Gonna disable them for the time beeing.

**Comment by Danekjovax** [comment]
Fair enough.  I won't miss them.  Thanks for your great work, Freebi!
