### ISSUE TITLE
Mekanism's Osmium Compressor not working (Recipes)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_Classic#3]
Hi, Freebi!

We're playing in 1.7 SMP.  Mainly we seem to not be able to use the Osmium compressor to make refined glowstone, which I believe uses this machine to create it - JEI is no longer reporting any Mekanism processing recipe to craft this refined glowstone ingot:
![2021-01-16_17 05 25](https://user-images.githubusercontent.com/10191173/104824097-0f5d4a00-581d-11eb-9bc4-0955736ec14d.png)

The GUI for the Osmium Compressor also doesn't show recipes when click on the process arrow in the center:
![2021-01-16_17 01 26](https://user-images.githubusercontent.com/10191173/104824122-44699c80-581d-11eb-8ebc-d9f475dc2ca0.png)

Please advise, good sir. ;2)

**Comment by Freebi85** [comment]
Thx for the heads up. Feelsbad
Fixed indev 👍

**Comment by Danekjovax** [comment]
Thanks, Freebi!
