### ISSUE TITLE
Quark End item cause crash

### ISSUE THREAD

**Issue by wicked9090** [Freebi85/Explorico_Classic#5]
[crash-2021-01-29_23.35.24-client.txt](https://github.com/Freebi85/Explorico_Easy/files/5893978/crash-2021-01-29_23.35.24-client.txt)
Tried to check recipe uses of the item from Quark (mined in the End, can't remember exact name, hope log has it..) and then crashed

**Comment by wicked9090** [comment]
Myalite Crystal from the Spiral Spires is the item after quickly googling

**Comment by Danekjovax** [comment]
I can verify this.  Should be any of the myalite items, but I've not been able to consistently repeat the crash.  After 1st crash my game recovers and I can continue to mine the material and even use it back at base.

**Comment by Freebi85** [comment]
It's trying to render some specific bluepower half block variatns when browsing through JEI. It happens in every dimension.

Opened ticket in Bluepower.
https://github.com/Qmunity/BluePower/issues/580

Gonna Remove myalite blocks from JEI for the time beeing.

**Comment by Freebi85** [comment]
https://github.com/Qmunity/BluePower/issues/580

Solved in next update.
