### ISSUE TITLE
Add Netherwood Sapling (Silent Gear) for Botany Pot Use

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_Classic#7]
Self-Explanatory.  Thanks.
![image](https://user-images.githubusercontent.com/10191173/109391513-7b83a100-78e5-11eb-8985-91f8fd8ad360.png)
![image](https://user-images.githubusercontent.com/10191173/109391522-850d0900-78e5-11eb-896e-3859fe477250.png)

Thanks! :2D

**Comment by Freebi85** [comment]
This is gonna be included in the new mod Botany Trees :0
