### ISSUE TITLE
Silent Gear Supercharged Enchanted Books Unuseable?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_Classic#8]
I picked up a Supercharged II book from some loot.  Examining it, JEI shows no uses for Supercharged books.  Description is "Powers up Silent Gear materials." and so I place a SG material on an anvil with the book, but I get the hated red X.  Please look into this.  Thanks.
![image](https://user-images.githubusercontent.com/10191173/110210249-c14ce600-7e5e-11eb-86c2-8d8ea08e354f.png)
![image](https://user-images.githubusercontent.com/10191173/110210261-cd38a800-7e5e-11eb-9331-b632f21cd8a5.png)

**Comment by Freebi85** [comment]
If i understand the wiki correctly this is done via a multiblock structure and not with vanilla anvill. Check this out:
https://github.com/SilentChaos512/SilentGems/wiki/Supercharger-(SGear)

**Comment by Danekjovax** [comment]
Hmm so it may be a substitute for the Supercharging material to be used on the supercharging "altar"  I'll try that next time I get a book like that.  Thanks.
