### ISSUE TITLE
what mod changes the /give command

### ISSUE THREAD

**Issue by DoomSquirter** [Freebi85/Explorico_Classic#9]
for some reason the /give command considers everything after the quantity as an error.

normal behavior allows nbt tags, etc.  I'm assuming something's overwriting the command but no clue which one it is

**Comment by Freebi85** [comment]
i'm not sure if it was a thing with older forge version or the pattern but it should work in next update.

That's a possible pattern with random enchantment: 
/give @s minecraft:iron_pickaxe{Damage:50,Enchantments:[{id:"minecraft:aqua_affinity",lvl:2}],repairCost:"5"} 1
